version: "3.9"
services:
    scrapy:
        build:
            context: .
            dockerfile: Dockerfile
        image: scrapy
        container_name: jl_scrapy
        ports:
            - 18888:8888
        volumes:
            - "../:/opt/scrapy"
        tty: true
        external_links:
            - "gitlab:gitlab.local"
networks:
    default:
        external: true
        name: dev_network
