version: "3.9"
services:
    scrapy:
        image: continuumio/anaconda3
        container_name: jl_scrapy
        ports:
            - 18888:8888
        volumes:
            - "../:/opt/scrapy"
        tty: true
